# This script generates a table of barcharts to compare the quantity of annotations
# generated by GOMAP across different organisms and in comparison to other existing
# annotation sets (e.g. from Gramene)
annotation_quantities = read.csv("data/mocks/annotation_quantities.mock.csv", header = T)

# @TODO generalize
plot_data = t(as.matrix(annotation_quantities[1:2,3:5]))
colnames(plot_data) = c("GOMAP", "Gramene")

par(family='serif')
y_coordinates = barplot(plot_data, horiz=T, las=1)
text(annotation_quantities[1,]$n_c+annotation_quantities[1,]$n_f+annotation_quantities[1,]$n_p/2, y_coordinates[1], 
     formatC(annotation_quantities[1,]$n_p, format='d', big.mark=','))
text(annotation_quantities[1,]$n_c+annotation_quantities[1,]$n_f/2, y_coordinates[1],
     formatC(annotation_quantities[1,]$n_f, format='d', big.mark=','))
text(annotation_quantities[1,]$n_c/2, y_coordinates[1],
     formatC(annotation_quantities[1,]$n_c, format='d', big.mark=','))

# more @TODOs
# - sort so that largest column top
# - choose nice colors
# - make a nicer axis at bottom
# - put labels on first barplot (molecular function, cellular component, etc.)