# Results
... a quantitative comparison of the datasets in Table.

```{r cleanup-table}
dt2 <- read.csv("../analyses/cleanup/results/cleanup_table.csv", header=T)
kable(dt2, booktabs=TRUE, caption = "Number of removed annotations during cleanup.", col.names=c("Genome", "Dataset", "Obsolete Annotations", "Duplicates")) %>%
 kable_styling(latex_options = c("striped")) %>%
 collapse_rows(columns = 1, latex_hline="major")
```

```{r annotation-quantities}
dt2 <- read.csv("../analyses/quantity/results/quantity_table.csv", header=T)
# Drop the absolute 'genes annotated' counts, we only want the percentual ones
dt2 <- dt2[, !names(dt2) %in% c("genes_annotated_c", "genes_annotated_f", "genes_annotated_p", "genes_annotated_a")]
headers_above = c(a = 3, b = 4, c = 4, d =4)
names(headers_above) <- c(" ", 
  paste0("Annotations", footnote_marker_alphabet(1, double_escape=T)),
  paste0("Annotated Genes [\\\\%]", footnote_marker_alphabet(2, double_escape=T)), 
  paste0("Median Ann. per G.", footnote_marker_alphabet(3, double_escape=T)))
kable(dt2, booktabs=T, caption = "Quantitative metrics of the cleaned functional annotation sets. C, F, P, and A refer to the aspects of the GO: Cellular Component, Biological Function, Molecular Process, and Any/All.", col.names=c("Genome", "Genes", "Dataset", "C", "F", "P", "A","C", "F", "P", "A","C", "F", "P", "A")) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  add_header_above(headers_above, escape=F)%>%
  column_spec(c(15), bold = T) %>%
  column_spec(c(7,11), bold=T, border_right = T) %>%
  collapse_rows(columns = 1:2, latex_hline="major") %>%
  footnote(alphabet=c(
    "How many annotations in the C, F, and P aspect does this dataset contain? A = How many in total? $A = C + F + P$",
    "How many genes in the genome have at least one GO term from the C, F, P aspect annotated to them? A = How many at least one from any aspect? ($A = C \\\\cup F \\\\cup P$)",
    "Take a typical gene that is present in the annotation set. How many annotations does it have in each aspect? A = How many in total? Ask your favorite statistician why $A \\\\neq C + F +P$"
  ), threeparttable=T, escape=F)
```
